export enum AuditAction {
  // Auth
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  PASSWORD_CHANGE = 'PASSWORD_CHANGE',
  PASSWORD_RESET_REQUEST = 'PASSWORD_RESET_REQUEST',
  PASSWORD_RESET_COMPLETE = 'PASSWORD_RESET_COMPLETE',

  // Profile
  UPDATE_PROFILE = 'UPDATE_PROFILE',
  UPDATE_EMAIL = 'UPDATE_EMAIL',
  UPDATE_PHONE = 'UPDATE_PHONE',
  DELETE_PROFILE = 'DELETE_PROFILE',

  // Notice
  CREATE_NOTICE = 'CREATE_NOTICE',
  UPDATE_NOTICE = 'UPDATE_NOTICE',
  DELETE_NOTICE = 'DELETE_NOTICE',

  // Class
  CREATE_CLASS = 'CREATE_CLASS',
  UPDATE_CLASS = 'UPDATE_CLASS',
  DELETE_CLASS = 'DELETE_CLASS',

  // Assessment
  CREATE_ASSESSMENT = 'CREATE_ASSESSMENT',
  UPDATE_ASSESSMENT = 'UPDATE_ASSESSMENT',
  DELETE_ASSESSMENT = 'DELETE_ASSESSMENT',
  SUBMIT_ASSESSMENT = 'SUBMIT_ASSESSMENT',

  // Issue
  CREATE_ISSUE = 'CREATE_ISSUE',
  UPDATE_ISSUE = 'UPDATE_ISSUE',
  RESOLVE_ISSUE = 'RESOLVE_ISSUE',
  DELETE_ISSUE = 'DELETE_ISSUE',

  // Routine
  CREATE_ROUTINE = 'CREATE_ROUTINE',
  UPDATE_ROUTINE = 'UPDATE_ROUTINE',
  DELETE_ROUTINE = 'DELETE_ROUTINE',

  // Teacher
  CREATE_TEACHER = 'CREATE_TEACHER',
  UPDATE_TEACHER = 'UPDATE_TEACHER',
  DELETE_TEACHER = 'DELETE_TEACHER',

  // Subject
  CREATE_SUBJECT = 'CREATE_SUBJECT',
  UPDATE_SUBJECT = 'UPDATE_SUBJECT',
  DELETE_SUBJECT = 'DELETE_SUBJECT',

  // System
  USER_REGISTERED = 'USER_REGISTERED',
  CR_APPROVED = 'CR_APPROVED',
  CR_REJECTED = 'CR_REJECTED',
}
